<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vpriya" failures="3" tests="3" name="Test" time="30.287" errors="0" timestamp="2023-04-06T00:37:55 IST">
  <testcase classname="test_class.Put_test_class" name="orchestrator" time="27.755">
    <failure type="java.lang.AssertionError" message="expected [2023-04-06] but found [2023-04-05]">
      <![CDATA[java.lang.AssertionError: expected [2023-04-06] but found [2023-04-05]
at test_class.Put_test_class.responseBodyValidator(Put_test_class.java:72)
at test_class.Put_test_class.orchestrator(Put_test_class.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- orchestrator -->
  <testcase classname="test_class.Patch_test_class" name="orchestrator" time="1.213">
    <failure type="java.lang.AssertionError" message="expected [2023-04-06] but found [2023-04-05]">
      <![CDATA[java.lang.AssertionError: expected [2023-04-06] but found [2023-04-05]
at test_class.Patch_test_class.responseBodyValidator(Patch_test_class.java:69)
at test_class.Patch_test_class.orchestrator(Patch_test_class.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- orchestrator -->
  <testcase classname="test_class.Post_test_tc1" name="orchestrator" time="0.986">
    <failure type="java.lang.AssertionError" message="expected [2023-04-06] but found [2023-04-05]">
      <![CDATA[java.lang.AssertionError: expected [2023-04-06] but found [2023-04-05]
at test_class.Post_test_tc1.responseBodyValidator(Post_test_tc1.java:71)
at test_class.Post_test_tc1.orchestrator(Post_test_tc1.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- orchestrator -->
</testsuite> <!-- Test -->
